import { useState } from 'react'
import { Link } from 'react-router'
import { FileText, Search, Trash2, ChevronUp, ChevronDown, Copy, Edit2, GitCompare, Eye, Download, MoreVertical } from 'lucide-react'
import { useResumes, useDeleteResume } from '../hooks/useApi'
import { Spinner, TableSkeleton, EmptyState } from '../components/ui/loading'
import { ErrorState } from '../components/ui/error-state'
import { useNotification } from '../components/ui/Notification'

export default function History() {
  const [search, setSearch] = useState('')
  const [sortBy, setSortBy] = useState('date')
  const [sortOrder, setSortOrder] = useState('desc')
  const [page, setPage] = useState(1)
  const [statusFilter, setStatusFilter] = useState('all')
  const [roleFilter, setRoleFilter] = useState('all')
  const [activeMenu, setActiveMenu] = useState(null)
  const deleteResume = useDeleteResume()
  const notification = useNotification()

  const { data, isLoading, error, refetch } = useResumes({
    search,
    sortBy,
    sortOrder,
    page,
    limit: 10,
  })

  const handleDelete = async (id, fileName) => {
    notification.confirm({
      title: 'Delete Resume',
      message: `Are you sure you want to delete "${fileName}"? This action cannot be undone.`,
      confirmLabel: 'Delete',
      cancelLabel: 'Cancel',
      onConfirm: async () => {
        await deleteResume.mutateAsync(id)
        setActiveMenu(null)
      },
    })
  }

  const handleDuplicate = (resume) => {
    notification.info('Duplicate feature coming soon')
    setActiveMenu(null)
  }

  const handleRename = (resume) => {
    notification.info('Rename feature coming soon')
    setActiveMenu(null)
  }

  const handleCompare = (resumeId) => {
    window.location.href = `/compare?resumeId=${resumeId}`
    setActiveMenu(null)
  }

  const handleViewReport = (resume) => {
    if (resume.analysisId) {
      window.location.href = `/analysis/${resume.analysisId}`
    } else {
      notification.warning('No analysis available for this resume')
    }
    setActiveMenu(null)
  }

  const handleExport = async (resume) => {
    try {
      const { getAnalysisByResume } = await import('../api/analysis')
      const response = await getAnalysisByResume(resume.id)
      const analysis = response.data.data || response.data
      const scores = analysis.scores || {}
      const date = analysis.createdAt ? new Date(analysis.createdAt).toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' }) : new Date().toLocaleDateString()
      const md = `# Resume Analysis Report

**Resume:** ${resume.fileName || 'Untitled Resume'}
**Date:** ${date}
**ATS Score:** ${analysis.atsScore || 0}/100
**Overall Score:** ${analysis.overallScore || 0}/100

## Scores

| Metric | Score |
|--------|-------|
| Overall | ${analysis.overallScore || 0}/100 |
| ATS Pass-rate | ${analysis.atsScore || 0}/100 |
| Keyword Density | ${analysis.keywordScore || 0}/100 |
| Formatting | ${analysis.formattingScore || 0}/100 |

## Strengths

${(analysis.strengths?.skills || []).map(s => `- ${s}`).join('\n') || '- None recorded'}

## Weaknesses

${(analysis.weaknesses || []).map(w => `- **${w.area}**: ${w.suggestion}`).join('\n') || '- None recorded'}

## Recommendations

${(analysis.improvementSuggestions || []).map((r, i) => `${i + 1}. **${r.category}**: ${r.suggestion}`).join('\n') || '- None'}

---
*Generated by ResuMetrics*
`
      const blob = new Blob([md], { type: 'text/markdown' })
      const url = URL.createObjectURL(blob)
      const a = document.createElement('a')
      a.href = url
      a.download = `${resume.fileName || 'resume'}-analysis.md`
      document.body.appendChild(a)
      a.click()
      document.body.removeChild(a)
      URL.revokeObjectURL(url)
      notification.success('Export downloaded successfully')
    } catch (e) {
      notification.error('Failed to export. Please try again.')
    }
    setActiveMenu(null)
  }

  const handleSort = (field) => {
    if (sortBy === field) {
      setSortOrder(sortOrder === 'asc' ? 'desc' : 'asc')
    } else {
      setSortBy(field)
      setSortOrder('desc')
    }
  }

  const SortIcon = ({ field }) => {
    if (sortBy !== field) return null
    return sortOrder === 'asc' ? <ChevronUp className="size-3" /> : <ChevronDown className="size-3" />
  }

  if (isLoading) {
    return (
      <div className="px-8 py-10">
        <div className="mb-8">
          <div className="h-8 w-48 animate-pulse bg-ink/10" />
          <div className="mt-2 h-4 w-96 animate-pulse bg-ink/10" />
        </div>
        <TableSkeleton rows={8} />
      </div>
    )
  }

  if (error) {
    return (
      <div className="px-8 py-10">
        <ErrorState
          title="Failed to load history"
          message="We couldn't load your diagnostic history. Please try again."
          onRetry={() => refetch()}
        />
      </div>
    )
  }

  const resumes = data?.data?.data || data?.data || []
  const pagination = data?.data?.meta || {}

  // Get unique roles for filter
  const uniqueRoles = [...new Set(resumes.map(r => r.targetRole).filter(Boolean))]

  // Filter resumes
  const filteredResumes = resumes.filter(r => {
    if (statusFilter !== 'all' && r.status !== statusFilter) return false
    if (roleFilter !== 'all' && r.targetRole !== roleFilter) return false
    return true
  })

  return (
    <div className="px-8 py-10">
      <div className="mb-8 flex flex-wrap items-end justify-between gap-4">
        <div>
          <span className="font-mono text-[11px] uppercase tracking-widest text-ink/40">Archive</span>
          <h1 className="mt-2 font-serif text-4xl italic">Diagnostic history</h1>
          <p className="mt-2 text-sm text-ink/60">Every analysis on this workspace, in chronological order.</p>
        </div>
        <div className="flex items-center gap-2 border border-border bg-paper px-3 py-2 text-sm text-ink/60 focus-within:border-accent transition-micro">
          <Search className="size-4" aria-hidden="true" />
          <input
            placeholder="Filter by file name..."
            className="bg-transparent outline-none placeholder:text-ink/40"
            value={search}
            onChange={(e) => setSearch(e.target.value)}
            aria-label="Filter resumes by file name"
          />
        </div>
      </div>

      {/* Filters */}
      <div className="mb-6 flex flex-wrap gap-3">
        <select
          value={statusFilter}
          onChange={(e) => setStatusFilter(e.target.value)}
          className="rounded border border-border bg-paper px-3 py-2 text-sm focus-visible-ring"
          aria-label="Filter by status"
        >
          <option value="all">All Status</option>
          <option value="COMPLETED">Completed</option>
          <option value="PENDING">Pending</option>
          <option value="PROCESSING">Processing</option>
          <option value="FAILED">Failed</option>
        </select>

        <select
          value={roleFilter}
          onChange={(e) => setRoleFilter(e.target.value)}
          className="rounded border border-border bg-paper px-3 py-2 text-sm focus-visible-ring"
          aria-label="Filter by role"
        >
          <option value="all">All Roles</option>
          {uniqueRoles.map(role => (
            <option key={role} value={role}>{role}</option>
          ))}
        </select>

        {(statusFilter !== 'all' || roleFilter !== 'all' || search) && (
          <button
            onClick={() => {
              setStatusFilter('all')
              setRoleFilter('all')
              setSearch('')
            }}
            className="text-xs text-accent hover:underline focus-visible-ring"
          >
            Clear filters
          </button>
        )}
      </div>

      {filteredResumes.length === 0 ? (
        <EmptyState
          title="No diagnostics found"
          message={search || statusFilter !== 'all' || roleFilter !== 'all' 
            ? "Try adjusting your filters or search query." 
            : "Upload your first resume to start analyzing."}
          action={() => window.location.href = '/upload'}
          actionLabel="Upload resume"
        />
      ) : (
        <>
          <div className="border border-border bg-paper">
            <table className="w-full text-sm">
              <thead>
                <tr className="border-b border-border text-left font-mono text-[10px] uppercase tracking-widest text-ink/40">
                  <th className="p-4">File</th>
                  <th>
                    <button onClick={() => handleSort('role')} className="flex items-center gap-1 hover:text-ink focus-visible-ring">
                      Target Role <SortIcon field="role" />
                    </button>
                  </th>
                  <th>
                    <button onClick={() => handleSort('score')} className="flex items-center gap-1 hover:text-ink focus-visible-ring">
                      ATS Score <SortIcon field="score" />
                    </button>
                  </th>
                  <th>
                    <button onClick={() => handleSort('date')} className="flex items-center gap-1 hover:text-ink focus-visible-ring">
                      Created Date <SortIcon field="date" />
                    </button>
                  </th>
                  <th>Status</th>
                  <th className="p-4 text-right">Actions</th>
                </tr>
              </thead>
              <tbody>
                {filteredResumes.map((r) => (
                  <tr key={r.id} className="border-b border-border last:border-0 hover:bg-paper-2 transition-micro">
                    <td className="p-4 font-mono text-xs">
                      <span className="inline-flex items-center gap-2">
                        <FileText className="size-3 text-ink/40" aria-hidden="true" />
                        {r.fileName}
                      </span>
                    </td>
                    <td className="text-xs text-ink/70">{r.targetRole || '—'}</td>
                    <td className="font-mono">{r.latestScore || '—'}</td>
                    <td className="font-mono text-xs text-ink/50">
                      {new Date(r.createdAt).toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' })}
                    </td>
                    <td>
                      <span className={`inline-flex items-center gap-1.5 font-mono text-xs ${
                        r.status === 'COMPLETED' ? 'text-emerald-600' :
                        r.status === 'PENDING' || r.status === 'PROCESSING' ? 'text-amber-600' :
                        r.status === 'FAILED' ? 'text-red-600' : 'text-ink/60'
                      }`}>
                        <span className={`size-1.5 rounded-full ${
                          r.status === 'COMPLETED' ? 'bg-emerald-600' :
                          r.status === 'PENDING' || r.status === 'PROCESSING' ? 'bg-amber-600' :
                          r.status === 'FAILED' ? 'bg-red-600' : 'bg-ink/40'
                        }`} aria-hidden="true" />
                        {r.status || 'PENDING'}
                      </span>
                    </td>
                    <td className="p-4 text-right">
                      <div className="relative">
                        <button
                          onClick={() => setActiveMenu(activeMenu === r.id ? null : r.id)}
                          className="text-ink/40 hover:text-ink focus-visible-ring"
                          aria-label={`Actions for ${r.fileName}`}
                          aria-expanded={activeMenu === r.id}
                        >
                          <MoreVertical className="size-4" />
                        </button>
                        {activeMenu === r.id && (
                          <>
                            <div
                              className="fixed inset-0 z-10"
                              onClick={() => setActiveMenu(null)}
                            />
                            <div className="absolute right-0 top-full z-20 mt-1 w-48 rounded border border-border bg-paper py-1 shadow-lg" role="menu">
                              <button
                                onClick={() => handleViewReport(r)}
                                className="flex w-full items-center gap-2 px-4 py-2 text-left text-sm hover:bg-paper-2 focus-visible-ring"
                                role="menuitem"
                              >
                                <Eye className="size-3" aria-hidden="true" /> View Report
                              </button>
                              <button
                                onClick={() => handleCompare(r.id)}
                                className="flex w-full items-center gap-2 px-4 py-2 text-left text-sm hover:bg-paper-2 focus-visible-ring"
                                role="menuitem"
                              >
                                <GitCompare className="size-3" aria-hidden="true" /> Compare
                              </button>
                              <button
                                onClick={() => handleDuplicate(r)}
                                className="flex w-full items-center gap-2 px-4 py-2 text-left text-sm hover:bg-paper-2 focus-visible-ring"
                                role="menuitem"
                              >
                                <Copy className="size-3" aria-hidden="true" /> Duplicate
                              </button>
                              <button
                                onClick={() => handleRename(r)}
                                className="flex w-full items-center gap-2 px-4 py-2 text-left text-sm hover:bg-paper-2 focus-visible-ring"
                                role="menuitem"
                              >
                                <Edit2 className="size-3" aria-hidden="true" /> Rename
                              </button>
                              <button
                                onClick={() => handleExport(r)}
                                className="flex w-full items-center gap-2 px-4 py-2 text-left text-sm hover:bg-paper-2 focus-visible-ring"
                                role="menuitem"
                              >
                                <Download className="size-3" aria-hidden="true" /> Export
                              </button>
                              <div className="border-t border-border" />
                              <button
                                onClick={() => handleDelete(r.id, r.fileName)}
                                className="flex w-full items-center gap-2 px-4 py-2 text-left text-sm text-red-600 hover:bg-red-50 focus-visible-ring"
                                role="menuitem"
                              >
                                <Trash2 className="size-3" aria-hidden="true" /> Delete
                              </button>
                            </div>
                          </>
                        )}
                      </div>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>

          {pagination.totalPages > 1 && (
            <div className="mt-4 flex items-center justify-between">
              <p className="text-sm text-ink/60">
                Showing {((page - 1) * pagination.limit) + 1} to {Math.min(page * pagination.limit, pagination.total)} of {pagination.total} results
              </p>
              <div className="flex gap-2">
                <button
                  onClick={() => setPage(p => Math.max(1, p - 1))}
                  disabled={page === 1}
                  className="rounded border border-border px-3 py-1 text-sm disabled:opacity-50 focus-visible-ring"
                >
                  Previous
                </button>
                <button
                  onClick={() => setPage(p => Math.min(pagination.totalPages, p + 1))}
                  disabled={page === pagination.totalPages}
                  className="rounded border border-border px-3 py-1 text-sm disabled:opacity-50 focus-visible-ring"
                >
                  Next
                </button>
              </div>
            </div>
          )}
        </>
      )}
    </div>
  )
}